In [ ]:
# !pip install requests pandas python-dotenv openai -q

In [51]:
import os 
import requests
import pandas as pd
import numpy as np
import json
import re
from openai import OpenAI
from dotenv import load_dotenv

## Linkedin Search

Change top funnel search here

In [ ]:
load_dotenv()

API_KEY = os.getenv("PROXYCURL_API_KEY")
if not API_KEY:
    raise ValueError('proxycurl api key unset')
print(f'env loaded with proxycurl api key: {API_KEY}')

PERPLEXITY_API_KEY=os.getenv('PERPLEXITY_API_KEY')
if not PERPLEXITY_API_KEY:
    raise ValueError('perplexity api key unset')
print(f'env loaded with perplexity api key: {PERPLEXITY_API_KEY}')

np.set_printoptions(precision=2, suppress=True, linewidth=120)

In [7]:
params = {
    'country' : 'US',
    'education_school_name' : 'Georgia Institute of Technology', # can add college of computing, isye, etc. later
    'current_role_title': "Founder OR Co-Founder OR \"Founding Engineer\" OR CEO OR CTO OR Stealth",
    'enrich_profiles' : 'enrich',
    'page_size' : 7, # limit results 
    'use_cache' : 'if-present' # should be if-recent for final 
}
# more opts: https://nubela.co/proxycurl/docs?python#search-api-person-search-endpoint
headers = {'Authorization' : f'Bearer {API_KEY}'}
response = requests.get('https://nubela.co/proxycurl/api/v2/search/person', params=params, headers=headers)
data = response.json()

In [ ]:
# Raw Proxycurl data
data

{'results': [{'linkedin_profile_url': 'https://www.linkedin.com/in/cantino',
   'profile': {'public_identifier': 'cantino',
    'profile_pic_url': 'https://s3.us-west-000.backblazeb2.com/proxycurl/person/cantino/profile?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=0004d7f56a0400b0000000001%2F20250228%2Fus-west-000%2Fs3%2Faws4_request&X-Amz-Date=20250228T062900Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=fa6aa03d6801cdb56e16660ac7cbe3ae070f982f481e60d753d13268a03db453',
    'background_cover_image_url': None,
    'first_name': 'Andrew',
    'last_name': 'Cantino',
    'full_name': 'Andrew Cantino',
    'follower_count': 1258,
    'occupation': 'Founder / Chief Strategy Officer at Overview Energy',
    'headline': 'Climate ◊ Space ◊ Science ◊ Software',
    'summary': "I am a hands-on technical leader specializing in strategic planning, technical prioritization, and engineering practices. I've founded companies, raised money, and built teams. I've also managed phila

In [215]:
# Parse raw data to df

def extract_undergrad_school(edu_list):
    for ed in edu_list:
        deg = (ed.get("degree_name") or "").lower()
        fos = (ed.get('field_of_study') or "").lower()
        if any((keyword in deg or keyword in fos) for keyword in ["bs", "ba", "bachelor", "bse", "bsba"]):
            return ed.get("school")
    return None

def extract_grad_school(edu_list):
    for ed in edu_list:
        fos = (ed.get('field_of_study') or "").lower()
        deg = (ed.get("degree_name") or "").lower()
        if any((keyword in deg or keyword in fos)for keyword in ["master", "mba", "ms", "phd"]):
            return ed.get("school")
    return None

def extract_current_experience(experiences):
    # Look for the experience with ends_at=None
    current_exp = next((exp for exp in experiences if exp.get("ends_at") is None), None)
    if current_exp:
        return (current_exp.get("company"), current_exp.get("title"))
    
    return (None, None)

def extract_previous_experience(experiences):
    if len(experiences) > 1:
        return [(exp.get("company"), exp.get("title")) for exp in experiences[1:]]

    return (None, None)

records = []
for result in data["results"]:
    profile = result.get("profile", {})
    full_name = profile.get("full_name")
    edu_list = profile.get("education", [])
    exp_list = profile.get("experiences", [])
    linkedin = result.get('linkedin_profile_url', [])
    
    undergrad = extract_undergrad_school(edu_list)
    grad = extract_grad_school(edu_list)
    current_company, current_title = extract_current_experience(exp_list)
    previous_experiences_titles = extract_previous_experience(exp_list) 
    
    row = {
        "Name": full_name,
        "Undergrad School": undergrad,
        "Graduate School": grad,
        "Current Company": current_company,
        "Current Title": current_title,
        "Previous Companies": [exp[0] for exp in previous_experiences_titles],
        "Previous Titles" : [exp[1] for exp in previous_experiences_titles],
        "Linkedin" : linkedin
    }
    records.append(row)

df = pd.DataFrame(records)

In [216]:
# Unranked Founder Data
df

Name                                   Undergrad School  \
0   Andrew Cantino                                  Haverford College   
1        Henry Shi                             University of Waterloo   
2        Jim Beach  University of Hawai‘i - Shidler College of Bus...   
3   Matt Greenberg                    Georgia Institute of Technology   
4  Shane Zilinskas                             University of Virginia   
5     Adam Crossno  Georgia State University - J. Mack Robinson Co...   
6        Adam Gent                    Georgia Institute of Technology   

                                     Graduate School  \
0                    Georgia Institute of Technology   
1                    Georgia Institute of Technology   
2  University of Hawai‘i - Shidler College of Bus...   
3                                               None   
4                                               None   
5                                               None   
6                                               None   

              Current Company                     Current Title  \
0             Overview Energy  Founder / Chief Strategy Officer   
1                   Super.com         Co-Founder & Board Member   
2     The School For Startups                  Business Builder   
3                   Handshake                               CTO   
4                 ClearSummit                    Founder & CEO    
5  OnAsset Intelligence, Inc.                               CEO   
6                     SnapHop                        Co-founder   

                                  Previous Companies  \
0  [The Navigation Fund, The Orbital Index, Overv...   
1  [Various Startups, Forbes, Google, uMentioned,...   
2  [JimBeach.com, School for Startups Radio, McGr...   
3  [Swoogo, Reforge, Credit Karma, CoSo Cloud, LL...   
4  [TuneRegistry, Mobelux, Media General, UVA Hea...   
5  [SAVR Communications, SAVR Communications, Met...   
6  [Evocatus, Inc., Reagent Software, Percussion ...   

                                     Previous Titles  \
0  [Climate Program Consultant, Co-Creator, Found...   
1  [Investor, Contributor, Software Engineer, Co-...   
2  [International Keynote Speaker, SBA Award Winn...   
3  [Advisor, CPTO, VP of Engineering, VP of Engin...   
4  [Co-Founder | CTO (Exited), Software Engineer,...   
5  [Vice President and General Manager, Product D...   
6  [Co-founder, President, Senior Web Application...   

                                     Linkedin  
0         https://www.linkedin.com/in/cantino  
1     https://www.linkedin.com/in/henrythe9th  
2     https://www.linkedin.com/in/jamesabeach  
3   https://www.linkedin.com/in/mattgreenberg  
4  https://www.linkedin.com/in/shanezilinskas  
5     https://www.linkedin.com/in/adamcrossno  
6         https://www.linkedin.com/in/agentgt

## Scoring Configuration

Consider [this](https://docs.google.com/document/d/1D7Zjma2FrrnSuoQTMsI0ec_5ENTzjN6wIpKoI4O1ASE/edit?tab=t.0) evaluation matrix. 

We could consider learning the tiers, but hardcoding it seems fine since we don't have enough data.

Here's the current matrix scoring schema:

| Category  | Encoding | Example                             | Dimension |
|-----------|----------|-------------------------------------|-----------|
| Undergrad | One hot  | [Tier 3, Tier 2, Tier 1 (other)]| 3  |
| Graduate | One hot | [Tier 3, Tier 2, Tier 1 (other), Fallback/None] | 4|
| Previous Exit | One hot | [100m+, 25m-100m, 1-25m, Fallback/None] | 4 |
| Previous Founder | One hot | [yes - success, yes, no] | 3 |
| Prior Startup Exp | One hot | [early + success, early, no] | 3|
| Company as Employee Quality | One hot | [Tier 3, Tier 2, Tier 1 (other)] | 3|
| Seniority | One hot | [Tier 3, Tier 2, Tier 1 (other)]| 3|
| Expertise | One hot | [Tier 3, Tier 2, Tier 1 (other)]|3|
||||26|

Tier 3 > Tier 2 > Tier 1


In [217]:
CFG = {
    # Undergrad scoring
    'UNDERGRAD': {
        'TIERS': {
            1: set(),  # Tier 1 (Other)
            2: {  # Tier 2
                "Carnegie Mellon University", "Brigham Young University", "Georgia Institute of Technology", 
                "Purdue", "Tsinghua University", "IIT Delhi", "Hebrew University", "University of Virginia", 
                "University of Washington", "Dartmouth", "Penn State University", "UC San Diego", 
                "University of Maryland", "University of Colorado", "Georgetown", "Reichman", 
                "Univeristy of British Columbia", "NSU", "IIT Kharagpur", "University of Florida", 
                "Ben Gurion University", "University of North Carolina", "Indiana University", "University of Oxford"
            },
            3: {  # Tier 3
                "Stanford", "Massachusetts Institute of Technology", "University of California, Berkeley", 
                "University of Pennsylvania", "Harvard", "Cornell", "Tel Aviv University", "UMich", 
                "University of Texas", "University of Illinois", "Columbia", "Yale", "UCLA", "Princeton", 
                "USC", "Technion - Israel Institute of Technology", "Duke", "Northwestern", "IIT Bombay", 
                "NYU", "University of Waterloo", "Brown", "McGill", "University of Wisconsin", "University of Toronto"
            }
        },
        'WEIGHT': 2,
        'DIMENSION': 3
    },
    
    # Graduate school scoring
    'GRADUATE': {
        'TIERS': {
            0: {'None'},  # Tier 0 - No graduate degree
            1: set(),  # Tier 1 (other) 
            2: set(),  # Tier 2 
            3: {  # Tier 3
                "Stanford", "Massachusetts Institute of Technology", "University of California, Berkeley", 
                "University of Pennsylvania", "Harvard", "Columbia", "Northwestern", 
                "New York University", "University of Cambridge", "University of Oxford"
            }
        },
        'WEIGHT': 2,
        'DIMENSION': 4
    },
    
    # Company quality scoring
    'COMPANY': {
        'TIERS': {
            1: set(),  # Tier 1 (other)
            2: {"Google", "Tesla"},  # Tier 2
            3: {"Anduril", "Palantir", "Ramp", "OpenAI", "Anthropic"}  # Tier 3
        },
        'WEIGHT': 4,
        'DIMENSION': 3
    },
    
    # Seniority scoring
    'SENIORITY': {
        'TIERS': {
            1: set(),  # Tier 1 (other)
            2: {'Head', 'Senior', 'Vice President'},  # Tier 2
            3: {'Executive', 'SVP', 'VP', "Senior Vice President", 'Director', 'Principal'}  # Tier 3
        },
        'WEIGHT': 3,
        'DIMENSION': 3
    },
    
    # Expertise scoring
    'EXPERTISE': {
        'TIERS': {
            1: set(),  # Tier 1 (other)
            2: set(),  # Tier 2
            3: {'Engineering', 'Product', 'Engineer'}  # Tier 3
        },
        'WEIGHT': 3,
        'DIMENSION': 3
    },
    
    # Previous exit scoring
    'EXIT': {
        'TIERS': {
            0: 'No',  # Tier 0
            1: '$1-25M',  # Tier 1
            2: '$25-100M',  # Tier 2
            3: '$100M+'  # Tier 3
        },
        'WEIGHT': 5,
        'DIMENSION': 4
    },
    
    # Previous founder experience scoring
    'FOUNDER': {
        'TIERS': {
            1: 'No',  # Tier 1
            2: 'Yes - unsuccessful',  # Tier 2
            3: 'Yes - successful'  # Tier 3
        },
        'WEIGHT': 1,
        'DIMENSION': 3
    },
    
    # Startup experience scoring
    'STARTUP': {
        'TIERS': {
            1: 'No startup experience',  # Tier 1
            2: 'Early at startup',  # Tier 2
            3: 'Early at successful startup'  # Tier 3
        },
        'WEIGHT': 1,
        'DIMENSION': 3
    }
}

### Scoring

UndergradScore, GraduateScore, CompanyQuality, SeniorityScore, and ExpertiseScore all come from proxycurl.

Evaluations of exit size, previous startup experience, and previous founder experience come from perplexity, which limits to around 7 seconds processing time per founder, since it seems we need to hit sonar-pro for accurate results.

## Scoring Configuration

Consider [this](https://docs.google.com/document/d/1D7Zjma2FrrnSuoQTMsI0ec_5ENTzjN6wIpKoI4O1ASE/edit?tab=t.0) evaluation matrix. 

We could consider learning the tiers, but hardcoding it seems fine since we don't have enough data.

Here's the current matrix scoring schema:

| Category  | Encoding | Example                             | Dimension |
|-----------|----------|-------------------------------------|-----------|
| Undergrad | One hot  | [Tier 3, Tier 2, Tier 1 (other)]| 3  |
| Graduate | One hot | [Tier 3, Tier 2, Tier 1 (other), Fallback/None] | 4|
| Previous Exit | One hot | [100m+, 25m-100m, 1-25m, Fallback/None] | 4 |
| Previous Founder | One hot | [yes - success, yes, no] | 3 |
| Prior Startup Exp | One hot | [early + success, early, no] | 3|
| Company as Employee Quality | One hot | [Tier 3, Tier 2, Tier 1 (other)] | 3|
| Seniority | One hot | [Tier 3, Tier 2, Tier 1 (other)]| 3|
| Expertise | One hot | [Tier 3, Tier 2, Tier 1 (other)]|3|
||||26|


In [218]:
# Ordinals
def get_tier(category, tier):
    try:
        return CFG[category]['TIERS'][tier]
    except Exception:
        print('could not get tier')

# Undergrad
df["UNDERGRAD"] = np.where(
    df["Undergrad School"].isin(get_tier('UNDERGRAD', 3)), 3,
    np.where(df["Undergrad School"].isin(get_tier('UNDERGRAD', 2)), 2, 1)
)

# Graduate
df["GRADUATE"] = np.where(
    df["Graduate School"].isin(get_tier('GRADUATE', 3)), 3, 
    np.where(df["Graduate School"].isin(get_tier('GRADUATE', 2)), 2,
        np.where(df["Graduate School"].notnull() & (df["Graduate School"] != "None"), 1, 0)
    )
)

# Company Quality
df["COMPANY"] = df.apply(
    lambda row: 3 if any(company in get_tier('COMPANY', 3) for company in row["Previous Companies"] if company) else
                2 if any(company in get_tier('COMPANY', 2) for company in row["Previous Companies"] if company) else 1,
    axis=1
)

df["SENIORITY"] = df.apply(
    lambda row: 3 if any(title and any(keyword.lower() in title.lower() for keyword in get_tier('SENIORITY', 3)) 
                         for title in row["Previous Titles"] if title) else
                2 if any(title and any(keyword.lower() in title.lower() for keyword in get_tier('SENIORITY', 2)) 
                         for title in row["Previous Titles"] if title) else 1,
    axis=1
)

df["EXPERTISE"] = df.apply(
    lambda row: 3 if any(title and any(kw.lower() in word.lower() 
                         for word in title.split() for kw in get_tier('EXPERTISE', 3))
                         for title in row["Previous Titles"] if title) else
                2 if any(title and any(kw.lower() in word.lower() 
                         for word in title.split() for kw in get_tier('EXPERTISE', 2))
                         for title in row["Previous Titles"] if title) else 1,
    axis=1
)


In [219]:
# Ordinal representation for api result columns
client = OpenAI(api_key=PERPLEXITY_API_KEY, base_url='https://api.perplexity.ai')

def get_ai_evaluation(person_data):
    
    # Profile
    name = person_data.get("Name", "Unknown")
    titles = ", ".join([t for t in person_data.get("Previous Titles", []) if t]) if person_data.get("Previous Titles") else "Unknown"
    companies = ", ".join([c for c in person_data.get("Previous Companies", []) if c]) if person_data.get("Previous Companies") else "Unknown"
   
    # prompt
    messages = [
        {
            "role": "system",
            "content": (
                "You are a venture research assistant. Your task is to evaluate a person's founder and startup experience "
                "based on the provided information. Provide concise and structured evaluations for the categories: "
                "'Previously an exited founder?', 'Previously a founder?', and 'Prior Startup Experience'. Use the following rating scales:\n\n"
                f"- Previously an exited founder?\n  3: {get_tier('EXIT', 3)}, 2: {get_tier('EXIT', 2)}, 1: {get_tier('EXIT',1)}, 0: {get_tier('EXIT',0)}\n"
                f"- Previously a founder?\n  3: {get_tier('FOUNDER', 3)}, 2: {get_tier('FOUNDER',2)}, 1: {get_tier('FOUNDER', 1)}'\n"
                f"- Prior Startup Experience\n  3: {get_tier('STARTUP', 3)}, 2: {get_tier('STARTUP', 2)}, 1: {get_tier('STARTUP', 1)}.\n"
                "Do not consider a a person's current experience as prior startup experience or previously a founder.\n\n"
                "Provide your response in JSON format with keys 'exited_founder', 'previous_founder', and 'startup_experience'.\n"
            ),
        },
        {
            "role": "user",
            "content": (
                f"Evaluate the following person's founder and startup experience:\n\n"
                f"Name: {name}\n"
                f"Titles: {titles}\n"
                f"Experiences: {companies}\n\n"
                "Provide ratings for the categories as described."
            ),
        },
    ]
    
    # Query response 
    fallback = {"exited_founder": 0, "previous_founder": 1, "startup_experience": 1}
    try:
        response = client.chat.completions.create(
            model="sonar-pro",
            messages=messages,
        )

        json_match = re.search(r'\{.*?\}', response.choices[0].message.content, re.DOTALL)
        if json_match:
            evaluation = json.loads(json_match.group())
            return evaluation
        else:
            print(f"Could not extract JSON for {name}")
            return fallback
        
    except Exception as e:
        print(f"Error evaluating {name}: {e}")
        return fallback

ai_evaluations = df.apply(get_ai_evaluation, axis=1)
df["EXIT"] = ai_evaluations.apply(lambda x: x.get("exited_founder", 0))
df["FOUNDER"] = ai_evaluations.apply(lambda x: x.get("previous_founder", 1))
df["STARTUP"] = ai_evaluations.apply(lambda x: x.get("startup_experience", 1))

In [220]:
# Ordinal representation
df

Name                                   Undergrad School  \
0   Andrew Cantino                                  Haverford College   
1        Henry Shi                             University of Waterloo   
2        Jim Beach  University of Hawai‘i - Shidler College of Bus...   
3   Matt Greenberg                    Georgia Institute of Technology   
4  Shane Zilinskas                             University of Virginia   
5     Adam Crossno  Georgia State University - J. Mack Robinson Co...   
6        Adam Gent                    Georgia Institute of Technology   

                                     Graduate School  \
0                    Georgia Institute of Technology   
1                    Georgia Institute of Technology   
2  University of Hawai‘i - Shidler College of Bus...   
3                                               None   
4                                               None   
5                                               None   
6                                               None   

              Current Company                     Current Title  \
0             Overview Energy  Founder / Chief Strategy Officer   
1                   Super.com         Co-Founder & Board Member   
2     The School For Startups                  Business Builder   
3                   Handshake                               CTO   
4                 ClearSummit                    Founder & CEO    
5  OnAsset Intelligence, Inc.                               CEO   
6                     SnapHop                        Co-founder   

                                  Previous Companies  \
0  [The Navigation Fund, The Orbital Index, Overv...   
1  [Various Startups, Forbes, Google, uMentioned,...   
2  [JimBeach.com, School for Startups Radio, McGr...   
3  [Swoogo, Reforge, Credit Karma, CoSo Cloud, LL...   
4  [TuneRegistry, Mobelux, Media General, UVA Hea...   
5  [SAVR Communications, SAVR Communications, Met...   
6  [Evocatus, Inc., Reagent Software, Percussion ...   

                                     Previous Titles  \
0  [Climate Program Consultant, Co-Creator, Found...   
1  [Investor, Contributor, Software Engineer, Co-...   
2  [International Keynote Speaker, SBA Award Winn...   
3  [Advisor, CPTO, VP of Engineering, VP of Engin...   
4  [Co-Founder | CTO (Exited), Software Engineer,...   
5  [Vice President and General Manager, Product D...   
6  [Co-founder, President, Senior Web Application...   

                                     Linkedin  UNDERGRAD  GRADUATE  COMPANY  \
0         https://www.linkedin.com/in/cantino          1         1        2   
1     https://www.linkedin.com/in/henrythe9th          3         1        2   
2     https://www.linkedin.com/in/jamesabeach          1         1        1   
3   https://www.linkedin.com/in/mattgreenberg          2         0        1   
4  https://www.linkedin.com/in/shanezilinskas          2         0        1   
5     https://www.linkedin.com/in/adamcrossno          1         0        1   
6         https://www.linkedin.com/in/agentgt          2         0        1   

   SENIORITY  EXPERTISE  EXIT  FOUNDER  STARTUP  
0          3          3     0        3        3  
1          1          3     0        3        3  
2          1          1     1        3        3  
3          3          3     0        1        3  
4          1          3     1        3        3  
5          2          3     0        1        2  
6          2          1     0        3        3

In [221]:
def one_hot_encode_column(values, dimension):
    if dimension == 3:
        # Ordinals are [1,2,3] => want indices [0,1,2]
        indices = values - 1
    else:
        # dimension = 4 => Ordinals are [0,1,2,3] => want indices [0..3]
        indices = values
    
    # Clip just in case
    indices = np.clip(indices, 0, dimension - 1)
    return np.eye(dimension, dtype=int)[indices]


# Apply one-hot encoding
one_hot_matrices = []
for cat, cfg in CFG.items():
    dim = cfg['DIMENSION']
    values = df[cat].to_numpy()  # Ordinal values in {0,1,2,3}
    matrix = one_hot_encode_column(values, dim)
    one_hot_matrices.append(matrix)

feature_matrix = np.concatenate(one_hot_matrices, axis=1)

df["feature_vector"] = list(feature_matrix)
feature_matrix.shape

(7, 26)

In [222]:
print(f'{feature_matrix}\n')
df[['Name','Current Company', 'Current Title', 'Linkedin', 'feature_vector']]

[[1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0 0 1]
 [0 0 1 0 1 0 0 0 1 0 1 0 0 0 0 1 1 0 0 0 0 0 1 0 0 1]
 [1 0 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1]
 [0 1 0 1 0 0 0 1 0 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0 0 1]
 [0 1 0 1 0 0 0 1 0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 0 1]
 [1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 1 0]
 [0 1 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0 1 0 0 1]]



Name             Current Company  \
0   Andrew Cantino             Overview Energy   
1        Henry Shi                   Super.com   
2        Jim Beach     The School For Startups   
3   Matt Greenberg                   Handshake   
4  Shane Zilinskas                 ClearSummit   
5     Adam Crossno  OnAsset Intelligence, Inc.   
6        Adam Gent                     SnapHop   

                      Current Title  \
0  Founder / Chief Strategy Officer   
1         Co-Founder & Board Member   
2                  Business Builder   
3                               CTO   
4                    Founder & CEO    
5                               CEO   
6                        Co-founder   

                                     Linkedin  \
0         https://www.linkedin.com/in/cantino   
1     https://www.linkedin.com/in/henrythe9th   
2     https://www.linkedin.com/in/jamesabeach   
3   https://www.linkedin.com/in/mattgreenberg   
4  https://www.linkedin.com/in/shanezilinskas   
5     https://www.linkedin.com/in/adamcrossno   
6         https://www.linkedin.com/in/agentgt   

                                      feature_vector  
0  [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, ...  
1  [0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, ...  
2  [1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, ...  
3  [0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, ...  
4  [0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, ...  
5  [1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, ...  
6  [0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, ...

### Ranking 

W : 26x26 

feature_matrix : N x 26

Compute scores as: $\mathrm{score_i} = x_i^T(\frac{(W+W^T)}{2})x_i$ for each row $x_i$

Weight matrix initialization: 
- Diagonal elements are individual contribution of each feature
- Off diagonal elements are interactions between different features. $w_{ij} >0 \Rightarrow$ having $i,j$ active together increases score more than individual contributions alone.

Note: 
- initialization below works because everything is one-hot and 3-tier. If that changes, need to adjust 


In [223]:
K = feature_matrix.shape[1]
W = np.zeros((K, K))

start_idx = 0
for cat, cfg in CFG.items():
    weight = cfg['WEIGHT']
    dim = cfg['DIMENSION']
    end_idx = start_idx + dim
    tiers = np.array(list(range(3, 3-dim,-1))[::-1]) * weight  
    indices = np.arange(start_idx, end_idx)
    W[indices, indices] = tiers
    start_idx = end_idx

# enforce symmetry:
# W = 0.5 * (W + W.T)

scores = np.sum((feature_matrix @ W) * feature_matrix, axis=1)
df["score"] = scores
results = df.sort_values(by="score", ascending=False)


In [224]:
# results.to_csv('out/results.csv')
results

Name                                   Undergrad School  \
0   Andrew Cantino                                  Haverford College   
1        Henry Shi                             University of Waterloo   
4  Shane Zilinskas                             University of Virginia   
3   Matt Greenberg                    Georgia Institute of Technology   
2        Jim Beach  University of Hawai‘i - Shidler College of Bus...   
5     Adam Crossno  Georgia State University - J. Mack Robinson Co...   
6        Adam Gent                    Georgia Institute of Technology   

                                     Graduate School  \
0                    Georgia Institute of Technology   
1                    Georgia Institute of Technology   
4                                               None   
3                                               None   
2  University of Hawai‘i - Shidler College of Bus...   
5                                               None   
6                                               None   

              Current Company                     Current Title  \
0             Overview Energy  Founder / Chief Strategy Officer   
1                   Super.com         Co-Founder & Board Member   
4                 ClearSummit                    Founder & CEO    
3                   Handshake                               CTO   
2     The School For Startups                  Business Builder   
5  OnAsset Intelligence, Inc.                               CEO   
6                     SnapHop                        Co-founder   

                                  Previous Companies  \
0  [The Navigation Fund, The Orbital Index, Overv...   
1  [Various Startups, Forbes, Google, uMentioned,...   
4  [TuneRegistry, Mobelux, Media General, UVA Hea...   
3  [Swoogo, Reforge, Credit Karma, CoSo Cloud, LL...   
2  [JimBeach.com, School for Startups Radio, McGr...   
5  [SAVR Communications, SAVR Communications, Met...   
6  [Evocatus, Inc., Reagent Software, Percussion ...   

                                     Previous Titles  \
0  [Climate Program Consultant, Co-Creator, Found...   
1  [Investor, Contributor, Software Engineer, Co-...   
4  [Co-Founder | CTO (Exited), Software Engineer,...   
3  [Advisor, CPTO, VP of Engineering, VP of Engin...   
2  [International Keynote Speaker, SBA Award Winn...   
5  [Vice President and General Manager, Product D...   
6  [Co-founder, President, Senior Web Application...   

                                     Linkedin  UNDERGRAD  GRADUATE  COMPANY  \
0         https://www.linkedin.com/in/cantino          1         1        2   
1     https://www.linkedin.com/in/henrythe9th          3         1        2   
4  https://www.linkedin.com/in/shanezilinskas          2         0        1   
3   https://www.linkedin.com/in/mattgreenberg          2         0        1   
2     https://www.linkedin.com/in/jamesabeach          1         1        1   
5     https://www.linkedin.com/in/adamcrossno          1         0        1   
6         https://www.linkedin.com/in/agentgt          2         0        1   

   SENIORITY  EXPERTISE  EXIT  FOUNDER  STARTUP  \
0          3          3     0        3        3   
1          1          3     0        3        3   
4          1          3     1        3        3   
3          3          3     0        1        3   
2          1          1     1        3        3   
5          2          3     0        1        2   
6          2          1     0        3        3   

                                      feature_vector  score  
0  [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, ...   36.0  
1  [0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, ...   34.0  
4  [0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, ...   31.0  
3  [0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, ...   30.0  
2  [1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, ...   25.0  
5  [1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, ...   24.0  
6  [0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, ...   23.0